sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t georgetatsis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true georgetatsis/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app : "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-838968213653"
  bucket_path: "docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

 